# Generated by Django 3.2 on 2023-06-29 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient', models.CharField(blank=True, max_length=150, verbose_name='Название продукта')),
                ('measure', models.CharField(blank=True, max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название тэга')),
                ('color', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Reciepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название рецепта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации рецепта')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность приготовления в минутах')),
                ('image', models.ImageField(default=None, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepts', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingridients_list', models.ManyToManyField(blank=True, related_name='reciepts', to='reciepts.Ingridients', verbose_name='Список ингридиентов')),
                ('tag_list', models.ManyToManyField(blank=True, related_name='reciepts', to='reciepts.Tags', verbose_name='Список тэгов')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
