# Generated by Django 3.2 on 2023-07-08 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reciepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='reciepts.reciepts', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reciepts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepts', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='reciepts',
            name='ingridients_list',
            field=models.ManyToManyField(blank=True, related_name='reciepts', through='reciepts.IngridientList', to='reciepts.Ingridients', verbose_name='Список продуктов'),
        ),
        migrations.AddField(
            model_name='reciepts',
            name='tag_list',
            field=models.ManyToManyField(blank=True, related_name='reciepts', to='reciepts.Tags', verbose_name='Список тэгов'),
        ),
        migrations.AddField(
            model_name='ingridientlist',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridients', to='reciepts.ingridients', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingridientlist',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_lists', to='reciepts.reciepts', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favorits',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit', to='reciepts.reciepts', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favorits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='not_unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='shopping',
            constraint=models.UniqueConstraint(fields=('user', 'reciept'), name='not_unique_shopping_list'),
        ),
        migrations.AddConstraint(
            model_name='favorits',
            constraint=models.UniqueConstraint(fields=('user', 'reciept'), name='not_unique_favorit'),
        ),
    ]
