# Generated by Django 3.2 on 2023-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reciepts", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingridientlist",
            constraint=models.UniqueConstraint(
                fields=("ingridient", "reciept"), name="not_unique_ingridient_list"
            ),
        ),
    ]
