version: '3'

volumes:
  pg_data:
  static:
  media:
  result_build:

services:
  
  db:
    image: postgres:13.10
    env_file: .env

    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    depends_on:
      - db
    image: maxer77/foodgram_backend
    env_file: .env
    
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend/:/app/result_build/
      - static:/result_build
    # image: maxer77/foodgram_frontend
    # env_file: .env

    # volumes:
    #   - static:/result_build/
  
  gateway:
    image: maxer77/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80

    volumes:
      - static:/staticfiles/
      - media:/media/
