version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13.10
    env_file: .env

    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    depends_on:
      - db
    image: maxer77/foodgram_backend
    env_file: .env
    
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: maxer77/foodgram_frontend
    env_file: .env

    volumes:
      - static:/result_build
  
  gateway:
    image: maxer77/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80

    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
