version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ../.env

    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build:
      context: ../backend/Foodgram
      dockerfile: Dockerfile
    env_file: ../.env
    
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile

    volumes:
      # - ../frontend/:/app/result_build/
      - static:/result_build

  gateway:

    build:
      context: ../nginx
      dockerfile: Dockerfile
    
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/app/media
 
