# Generated by Django 3.2 on 2023-06-29 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Пароль состоит только букв и цифрв. Должно быть хотя бы одна буква и одна цифра (не менее 8 символов)', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')], verbose_name='Пароль пользователя'),
        ),
    ]
